### ISSUE TITLE
Change install location to not be dependent on a user's home folder

### ISSUE THREAD

**Issue by tomkinsc** [dnanexus/dx-streaming-upload#1]
Looking at the role more, this looks great! A couple initial thoughts:

Currently in the work-in-progress [branch](https://github.com/dnanexus-rnd/dx-streaming-upload/blob/ymen-wip/tasks/main.yml), most files are copied to `~/`. Perhaps the install location for the uploader should not be relative to the (ansible) user's home directory. Placing the files in `/opt` as per the [Linux FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) might be appropriate if there permissions allow read/execute by the cronjob user.

Additionally, it might be nice to have the user specified for the cron jobs be a role variable (defaulting to root? or ansible_user?) The variable `ansible_ssh_user` is [deprecated](https://docs.ansible.com/ansible/intro_inventory.html) in favor of `ansible_user`. Or maybe there should be an ability to specify multiple users, each with a monitored directory he or she has read access to. Something like this (with singular user as the default in `defaults/main.yml`):

``` yaml
monitored_users:
  - username: user-one 
    monitored_directories:
      - /path/to/a/run/directory/parent/dir
      - /some/other/directory
  - username: user-two
    monitored_directories:
      - /miseqtwo/run/storage
```

Having multiple users might complicate dx token usage though? Since the token persists in a user's home directory after logging in via `dx login`, and the cron user may or may not have logged in? Tokens could be passed in as part of the list of users, and use `dx_token` if one is not specified:

``` yaml
dx_token: "PROJECTTOKEN"
monitored_users:
  - username: user-one
    dx_user_token: "TOKENVALUE"
    monitored_directories:
      - /path/to/a/run/directory/parent/dir
      - /some/other/directory
  - username: user-two
    monitored_directories:
      - /miseqtwo/run/storage
```

Using the user list would require something like this:

``` yaml
# Logging into DNAnexus account
- name: Log in to DNAnexus account if token is provided
  command: source ~/dx-toolkit/environment && dx login --token {{ item.dx_user_token if 'dx_user_token' in item else dx_token }} --noprojects
  become:
  become_user: {{ item.username }}
  args:
    executable: /bin/bash
  with_items: "{{monitored_users}}"
  when: dx_token is defined

 #...

- name: set up CRON job to run every hour in deploy mode
  cron: >
    name="DNAnexus monitor runs (deploy)"
    special_time=hourly
    user="{{item.0.username}}"
    job="flock -n ~/dnanexus/cron.lock bash -ex -c 'source ~/dx-toolkit/environment; PATH=$PATH:~/dnanexus-upload-agent; python ~/dnanexus/scripts/monitor_runs.py -c ~/dnanexus/config/monitor_runs.config -p {{ upload_project }} -d {{item.1}} -v > ~/monitor.log 2>&1' > ~/dx-stream_cron.log 2>&1"
  with_subelements:
        - monitored_users
        - monitored_directories
  when: mode == "deploy"

```

Example debug output:

``` yaml
    - debug: msg="User {{item.0.username}} should monitor {{item.1}}"
      with_subelements:
        - monitored_users
        - monitored_directories

    - debug: msg="User {{ item.username }} has token {{ item.dx_user_token if 'dx_user_token' in item else dx_token }}"
      with_items: "{{monitored_users}}"
```

```
ok: [localhost] => (item=({u'username': u'user-one', u'dx_user_token': u'TOKENVALUE'}, u'/path/to/a/run/directory/parent/dir')) => {
    "item": [
        {
            "dx_user_token": "TOKENVALUE",
            "username": "user-one"
        },
        "/path/to/a/run/directory/parent/dir"
    ],
    "msg": "User user-one should monitor /path/to/a/run/directory/parent/dir"
}
ok: [localhost] => (item=({u'username': u'user-one', u'dx_user_token': u'TOKENVALUE'}, u'/some/other/directory')) => {
    "item": [
        {
            "dx_user_token": "TOKENVALUE",
            "username": "user-one"
        },
        "/some/other/directory"
    ],
    "msg": "User user-one should monitor /some/other/directory"
}
ok: [localhost] => (item=({u'username': u'user-two'}, u'/miseqtwo/run/storage')) => {
    "item": [
        {
            "username": "user-two"
        },
        "/miseqtwo/run/storage"
    ],
    "msg": "User user-two should monitor /miseqtwo/run/storage"
}

TASK [debug] *******************************************************************
ok: [localhost] => (item={u'username': u'user-one', u'monitored_directories': [u'/path/to/a/run/directory/parent/dir', u'/some/other/directory'], u'dx_user_token': u'TOKENVALUE'}) => {
    "item": {
        "dx_user_token": "TOKENVALUE",
        "monitored_directories": [
            "/path/to/a/run/directory/parent/dir",
            "/some/other/directory"
        ],
        "username": "user-one"
    },
    "msg": "User user-one has token TOKENVALUE"
}
ok: [localhost] => (item={u'username': u'user-two', u'monitored_directories': [u'/miseqtwo/run/storage']}) => {
    "item": {
        "monitored_directories": [
            "/miseqtwo/run/storage"
        ],
        "username": "user-two"
    },
    "msg": "User user-two has token PROJECTTOKEN"
}
```

Also, I'm not sure if this is something for the role, or for the DNAnexus project, but it might be nice to organize data on the DNAnexus side into folders based on the `ansible_hostname`, so we can quickly see which files have been uploaded from a given site. Something like:

```
  DNAnexus_project/
    node-3/
      runs/
      demux/
    {{some_other_hostname }}/
      runs/
      demux/
```
